#!/usr/bin/env ruby

require 'httpclient'
require 'json'
require 'highline/import'

proxy = ENV['http_proxy']
CLIENT = HTTPClient.new(proxy)
#CLIENT = set_cookie_store("cookie.dat")


def parse_auth(authinfo)
  auth=""
  authinfo.split("\n").each { |line|
    m = /^Auth=(.*)$/.match(line)
    if m != nil && m.size == 2
      auth = m[1]
      break
    end
  }
  return auth
end


def get_auth(email, password)
  result = CLIENT.post("https://www.google.com/accounts/ClientLogin", 
                       :body => { 
                       "accountType" => "GOOGLE", 
                       "Email" => email,
                       "Passwd" => password, 
                       "service"=>"cp", 
                       "source"=> "cinsk-cinskapp-1" } )
  parse_auth(result.body)
end


def get_contacts(auth)
  result = CLIENT.get("https://www.google.com/m8/feeds/contacts/default/full",
                      { "v"=> 3,
                        "max-results" => 1000,
                        "alt" => "json" },
                      {"Authorization" => "GoogleLogin auth=#{auth}"})
  JSON.parse(result.body)
end

if ARGV.size == 2
  ACCOUNT = ARGV[0]
  PASSWORD = ARGV[1]
elsif ARGV.size == 1
  ACCOUNT = ARGV[0]
  PASSWORD = ask("password: ") { |q| q.echo = "*" }
else
  ACCOUNT = ask("gmail account: ")
  PASSWORD = ask("password: ") { |q| q.echo = "*" }
end


contacts = get_contacts(get_auth(ACCOUNT, PASSWORD))

File.open("contacts.el", "w") { |out|

  out.write ";;;\n"
  out.write ";;; Automatically generated by #{File.basename($PROGRAM_NAME)}\n"
  out.write ";;;\n"

  out.write "(setq my-google-contacts\n"
  out.write "      '(\n"

  contacts["feed"]["entry"].each { |map|
    name = nil
    begin
      name = map["gd$name"]["gd$fullName"]["$t"]
    rescue
    end

    if map["gd$email"] != nil
      size = map["gd$email"].size
      map["gd$email"].each { |ent|
        if name 
          if size == 1
            out.write "        (\"#{name}\" . \"#{ent["address"]}\")\n"
          else
            domain = ent["address"].gsub(/^[^@]*@(.*)$/, "\\1")
            out.write "        (\"#{name} (#{domain})\" . \"#{ent["address"]}\")\n"
          end
        end
        out.write "        (\"#{ent["address"]}\" . \"#{ent["address"]}\")\n"
      }
    end
  }
  out.write "      ))\n"
}

